### PR TITLE
Update release to v1.5.0

### LINKED ISSUE #360: latest release as CLI / edit local files with latest release
Is v1.0.1 the last release where a cli was provided? I'm looking for a way to edit local style files with the latest release version. Currently I help myself by starting the maputnik_windows.exe with watch flag on my style file and subsequently starting the dev server with the latest release. For some (black magic ;) reasons, I can edit the local file with the dev server version as long as the cli runs. Anyhow that doesn't feel like a proper solution, so I'm wondering if there's another way to edit local files with the latest version.

### PR DESCRIPTION
**Pull request by lukaswelte**
This PR updates the desktop CLI to editor v1.5.0 (and with that closes https://github.com/maputnik/editor/issues/360).
In order to simplify the build structure I removed the submodule and instead fetch the release bundle of the editor.
That means building does not require building the editor, which is not only less error prone since there are less steps, but also does one no longer need node installed to build the desktop project.

In addition I let travis cross compile the binary for windows, mac and linux so that appveyor should hopefully no longer be needed.

Before merging we should test that windows still works when building like this (I tested Mac and Linux).

### CODE REVIEW

**Comment by lukaswelte** [comment]
@orangemug this also uploads artifacts in a different style (the folders for each build). Do you have access to the bucket? 
Would you have points against using GitHub releases and pushing the artifacts there?

**Comment by pathmapper** [comment]
@lukaswelte, cool!

Just tried to build the binaries to test it also on Windows but got an error after `make` (go1.11.5 on Linux):

<details><summary>Error</summary>
<p>

```
go get -u golang.org/x/sys/...
go get github.com/gorilla/handlers
go get github.com/gorilla/mux
go get github.com/gorilla/websocket
go get github.com/fsnotify/fsnotify
go get github.com/urfave/cli
go get github.com/elazarl/go-bindata-assetfs/...
go get github.com/jteeuwen/go-bindata/...
go get github.com/mitchellh/gox
mkdir -p editor
cd editor && rm -rf public && curl -L https://github.com/maputnik/editor/releases/download/v1.5.0/public.zip --output public.zip && unzip public.zip && rm public.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   600    0   600    0     0   1171      0 --:--:-- --:--:-- --:--:--  1171
100 6723k  100 6723k    0     0  2652k      0  0:00:02  0:00:02 --:--:-- 4542k
Archive:  public.zip
   creating: public/
  inflating: public/0ded068875919a38d2f7.vendor.js  
  inflating: public/3fd0af39fad41bfc4cd6.js  
  inflating: public/app.7ac55b2eaff5a9da748f.js  
  inflating: public/bundle-stats.html  
  inflating: public/bundle-stats.json  
  inflating: public/favicon.ico      
   creating: public/fonts/
  inflating: public/fonts/Roboto-Medium.ttf  
  inflating: public/fonts/Roboto-Regular.ttf  
   creating: public/img/
  inflating: public/img/logo-color.svg  
  inflating: public/index.html       
  inflating: public/manifest.json    
go-bindata-assetfs --prefix "editor/" editor/public/...
/bin/sh: 1: go-bindata-assetfs: not found
Makefile:29: die Regel für Ziel „bindata_assetfs.go“ scheiterte
make: *** [bindata_assetfs.go] Fehler 127
```
</p>

**Comment by pathmapper** [comment]
I think it's related to my local go installation, I'll try to fix it.

**Comment by lukaswelte** [comment]
Great feedback @pathmapper. Would be great to know what the cause was for you (Travis is building successfully on Linux) and if Windows binary worked as well. 

You can download the built Windows binary from [this Link](https://we.tl/t-idvSZ8Xbzh) to test if it works. This is the one I built on my mac, but if that works it should also work when travis builts it on linux.

**Comment by pathmapper** [comment]
OK, works great now!

The issue on my side was that I didn't add GOPATH/bin to PATH (https://stackoverflow.com/a/36083961/8590463), first time using Go :blush:

Tried my binaries on Linux (Debian) and Windows 7 / 10.

Also yours is working on Windows 7 / 10. :tada:

**Comment by pathmapper** [comment]
@lukaswelte just a small thing, the version needs to be updated here as well:
https://github.com/maputnik/desktop/blob/d3ecef3de6862117e91569cb42baef70f3488331/maputnik.go#L19

**Comment by lukaswelte** [comment]
@pathmapper that is discussable. I think we should introduce desktop version and editor version. Cause it could be the case that we want to add features to desktop project while still having the same editor version. 

But I do agree that we should at least increment the version (doing this in a little commit now). 

@pathmapper do you habe the Access rights to remove appveyor?

**Comment by pathmapper** [comment]
> @orangemug this also uploads artifacts in a different style (the folders for each build). Do you have access to the bucket?
> Would you have points against using GitHub releases and pushing the artifacts there?

I think the bucket is not in use anymore and we are having the following options:

1. Building the binaries locally and upload them for each release manually after renaming them. I just did this for the [v1.5.0 release](https://github.com/maputnik/editor/releases/tag/v1.5.0) because some people were waiting for it (left an update note there so that people are aware that these binaries were not released from @orangemug).

2. Using GitHub releases of the desktop repo here (I guess this is what you've meant @lukaswelte ). For the CLI binaries we could link then from the editor releases to the desktop releases here.

3. Maybe switching from Travis to Circle CI is also an option. We are storing build artifacts for the Editor with Circle CI, e.g. https://1136-67726921-gh.circle-artifacts.com/0/artifacts/build/index.html#1.3/0/0

I'm leaning towards the second option, because I think it would be easier to work on the CLI (bug fixes, new features like proposed in https://github.com/maputnik/desktop/pull/2) and keep the Readme here in snc with the latest CLI version (compared to have the CLI released only with each new editor release) . But I'm also fine with other options.

**Comment by lukaswelte** [comment]
@pathmapper what do you think about the version field I just pushed here? It is more difficult since it is two instead of one version, but could allow to make it more clear what actually evolved.


Regarding the build stuff I'm good with GitHub Releases as well as Circle. But I would love to be able to iterate on the desktop version without needing version increments of the editor. 
And things like GitHub releases here or artifacts on Circle allow us to have that. And in the editor readme etc. we can just set links to the artifacts, so that all users also find it there.

**Comment by pathmapper** [comment]
@lukaswelte we are on the same page. 

> But I would love to be able to iterate on the desktop version without needing version increments of the editor.

:+1: This is exactly what I tried to say with my comment above.

> what do you think about the version field I just pushed here?

I think it's a great idea to make clear which editor version is in use for a specific desktop version.

My understanding was that until your PR the desktop version was the same as the used editor version because the `--version` option shows  `maputnik version ... `. But I could be wrong.

Anyway, we have to start/continue somewhere with the version number for the desktop version and I'm fine that your PR here is `Desktop: 1.0.3`. You could make it also `2.0.0`. or `1.1.0`, it's your decision :smile:.

> do you have the Access rights to remove appveyor?

No, I don't, I think @orangemug and/or @lukasmartinelli are having access rights.
Just let's remove appveyor.yml and the build status icon from the readme for now?

Regarding the build stuff:
If you would like to do it with Github Releases I would say just go for it. We are happy that someone is taking care of the repo here. Thanks again!

**Comment by lukaswelte** [comment]
If you do `maputnik --version` it will print `maputnik version Editor: 1.5.0; Desktop: 1.0.3` right now. 
I'm not sure if it will lead to confusion but I think it is clear enough.

Cool, I've never looked into the CircleCI artifacts stuff, but I'm sure we'll find a great way to do this.
But I think it would be great to have this in a separate issue/PR as this PR here is already pretty bloated with 10 different things going on the same time ;)

**Comment by pathmapper** [comment]
Yeah, it should be clear - Editor/Desktop are the names of the repos.

You're right, merging!

**Pull request merged**
