### PR TITLE
Refactor into a go module, update dependencies

### PR DESCRIPTION
**Pull request by kevinschaul**

### CODE REVIEW

**Comment by nyurik** [comment]
Is this one ready to merge?

**Comment by kevinschaul** [comment]
I just fixed the version number. I believe it is ready to merge @nyurik

**Comment by nyurik** [comment]
thanks!!!

**Comment by nyurik** [comment]
@kevinschaul I just moved Maputnik editor to the MapLibre organization, and I would love for this repo to be merged into that as well.  Do you have any time help with the migration? Thx!

P.S. I think we can consolidate the content of this repo into https://github.com/maplibre/maputnik as a `/desktop` subdirectory.

**Comment by kevinschaul** [comment]
Hi @nyurik just seeing this now. I can work on this in the next week.

**Comment by nyurik** [comment]
@kevinschaul that would be awesome, thanks!!!  Can you do a Pull Request into the desktop repo, moving all files into the `/desktop` directory and adjusting any github CI workflows. This way I can merge it into the maputnik repo while preserving the full history of this one.

**Comment by kevinschaul** [comment]
That sounds great. Just to confirm, in this repo (maputnik/desktop) I should make a PR that moves all files into a new folder called `desktop`, and fix the CI workflows. And then you can merge that all into maplibre/maputnik?

**Comment by nyurik** [comment]
exactly.  Basically pretend like this repo has all the content of maputnik, and you are creating a new `/desktop` dir, and it has to peacefully coexist with all the other content in this repo

**Comment by nyurik** [comment]
P.S. its ok if it  doesn't pass ci, etc -- I will merge it in and we can fix any outstanding issues

**Pull request merged**
